// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bullbearpanda
// github.com/bullbearpanda
// twitter.com/bullbearpanda

//@version=5
indicator("Panda Trend", overlay = true)
import TradingView/ta/7

//------------------------------------------------------------------------------
//-------------------------------------------------------------------- Variables
//------------------------------------------------------------------------------

tcm = input.float(0.5, title="Impulse Strength", minval=0.1, maxval=1.0, step = 0.1)

fast_period = input.int(200, "Fast Period EMA")
slow_period = input.int(200, "Slow Period SMA")

fast = ta.ema(close, fast_period)
slow = ta.sma(close, slow_period)

atr = ta.atr(10)

//------------------------------------------------------------------------------
//---------------------------------------------------------------------- Utility
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
//-------------------------------------------------------------- Candle Analysis
//------------------------------------------------------------------------------

significant_candle = ta.tr > (atr + (atr * tcm))

candle_range = (high - low) / 4
high_close = close <= high and (high - candle_range) < close
low_close = close >= low and (low + candle_range) > close
mid_close = (high - candle_range) > close and (low + candle_range) < close

bullish_impulse = high_close and significant_candle
bearish_impulse = low_close and significant_candle

//------------------------------------------------------------------------------
//------------------------------------------------------------------ Trend Logic
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
//------------------------------------------------------------------------ Plots
//------------------------------------------------------------------------------

barclr = bullish_impulse ? color.lime : bearish_impulse ? color.red : color.gray
barcolor(barclr)

fast_avg = plot(fast, color = color.new(color.yellow, 100))
slow_avg = plot(slow, color = color.new(color.orange, 100))
fill_clr = fast > slow ? color.new(color.lime, 25) : color.new(color.red, 75)
fill(fast_avg, slow_avg, color = fill_clr)
